# Example per-device config
# See https://wiki.hyprland.org/Configuring/Keywords/#per-device-input-configs for more
#device {
#    name = epic-mouse-v1
#    sensitivity = -0.5
#}

device {
    name = kbdfans-kbd67mkiirgbv3-keyboard 
    kb_layout=us,gr
    kb_options=grp:win_space_toggle   
}
