# Execute your favorite apps at launch
exec-once = waybar
exec-once = dunst
exec-once = swaybg m solid_color c '#000000'
exec-once = gsettings set org.gnome.desktop.interface cursor-theme dracula-cursors
exec-once = hyprctl setcursor dracula-cursors 0 
exec-once = hyprshade on blue-light-filter
