[manager]
#cwd = { fg = "white", bold = true }
#find_position = { fg = "black", bg = "lightcyan"}
#mode_normal = { fg = "black", bg = "black"}
#hovered = { bold = true, reversed = true }
border_symbol = " "
preview_hovered = { underline = false }

[flavor]
dark = "gruvbox-dark"
