[manager]
border_symbol = " "
#find_position = { fg = "black", bg = "lightcyan"}
#tab_active = { fg = "black", bg = "lightcyan"}
#hovered = { fg = "black", bg = "lightcyan"}
preview_hovered = { underline = false }
